#!/bin/bash

#@TODO - add check to make sure that dotfiles directory exists in the first place
ln -sf ~/dotfiles/gitconfig  ~/.gitconfig
ln -sf ~/dotfiles/gitignore  ~/.gitignore
ln -sf ~/dotfiles/profile    ~/.profile
ln -sfr ~/dotfiles/ssh        ~/.ssh/config
ln -sf ~/dotfiles/tmux.conf  ~/.tmux.conf
ln -sf ~/dotfiles/todo       ~/.todo
ln -sf ~/dotfiles/vimrc      ~/.vimrc
ln -sf ~/dotfiles/zshrc      ~/.zshrc
ln -sf ~/dotfiles/Xresources ~/.Xresources
