#!/bin/bash

ln -sf dotfiles/.gitconfig ~/.gitconfig
ln -sf dotfiles/.gitignore ~/.gitignore
ln -sf dotfiles/.profile   ~/.profile
ln -sf dotfiles/.tmux.conf ~/.tmux.conf
ln -sf dotfiles/.vimrc     ~/.vimrc
ln -sf dotfiles/.zshrc     ~/.zshrc
