#!/bin/bash

cd ~/
mkdir ~/archive
mkdir ~/archive/ccc ~/archive/youtube
mkdir ~/books
mkdir ~/builds
mkdir ~/code
mkdir ~/code/david.kiar.ie ~/code/playground ~/code/projects ~/code/work
mkdir ~/documents
mkdir ~/documents/finances ~/documents/travel ~/documents/work

git clone git@github.com:dkiarie/dotfiles ~/dotfiles
git clone git@github.com:dkiarie/notes ~/notes

# ~/scripts/link_dots
