#!/bin/bash

cd ~/
mkdir ~/archive
mkdir ~/archive/ccc ~/archive/youtube
mkdir ~/books
mkdir ~/builds
mkdir ~/code
mkdir ~/code ~/code/playground ~/code/playground/go ~/code/work
mkdir ~/documents
mkdir ~/documents/finances ~/documents/travel ~/documents/work

git clone git@github.com:dkiarie/dotfiles ~/dotfiles
git clone git@github.com:dkiarie/notes ~/notes
git clone git@github.com:dkiarie/david.kiar.ie ~/code/david.kiar.ie
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# ~/scripts/link_dots

# @todo automate this so I can use nodemon and VSCode together
# echo 'fs.inotify.max_user_watches=524288' | sudo tee -a /etc/sysctl.conf
# sudo sysctl -p
