#!/bin/bash

REPO_PATH=$1

cd $REPO_PATH

if git merge-base --is-ancestor origin/master master; then
    echo "It's not time to rebase!"
else
    echo "  _   _             _______    _____      _                    ";
    echo " | | (_)           |__   __|  |  __ \    | |                   ";
    echo " | |_ _ _ __ ___   ___| | ___ | |__) |___| |__   __ _ ___  ___ ";
    echo " | __| | '_ \` _ \ / _ \ |/ _ \|  _  // _ \ '_ \ / _\` / __|/ _ \ ";
    echo " | |_| | | | | | |  __/ | (_) | | \ \  __/ |_) | (_| \__ \  __/";
    echo "  \__|_|_| |_| |_|\___|_|\___/|_|  \_\___|_.__/ \__,_|___/\___|";
    echo $REPO_PATH
fi
